### ISSUE TITLE
runGodot c++ version, could you offer one

### ISSUE THREAD

**Issue by FashGek** [migueldeicaza/libgodot#7] opened 2024-02-19 15:15 UTC
### Godot version

4.2 

### System information

win10 + godot 4.2

### Issue description

in swift the runGodot function is below:
public func runGodot (args: [String], initHook: @escaping (GDExtension.InitializationLevel) -> (), loadScene: @escaping (SceneTree)->(), loadProjectSettings: @escaping (ProjectSettings)->(), verbose: Bool = false) {
    guard loadSceneCb == nil else {
        print ("runGodot was already invoked, it can currently only be invoked once")
        return
    }
    loadSceneCb = loadScene
    loadProjectSettingsCb = loadProjectSettings
    initHookCb = initHook
    
    libgodot_gdextension_bind { godotGetProcAddr, libraryPtr, extensionInit in
        if let godotGetProcAddr {
            let bit = unsafeBitCast(godotGetProcAddr, to: OpaquePointer.self)
            setExtensionInterface(to: bit, library: OpaquePointer (libraryPtr!))
            library = OpaquePointer (libraryPtr)!
            extensionInit?.pointee = GDExtensionInitialization(
                minimum_initialization_level: GDEXTENSION_INITIALIZATION_CORE,
                userdata: nil,
                initialize: embeddedExtensionInit,
                deinitialize: embeddedExtensionDeinit)
            return 1
        }
        
        return 0
    } _: { startup in
        if let cb = loadSceneCb, let ptr = startup {
            cb (SceneTree.createFrom(nativeHandle: ptr))
        }
    }

    //libgodot_bind(initBind, sceneBind, projectSettingsBind)
    var copy = args
    copy.insert("SwiftGodotKit", at: 0)
    if verbose {
        copy.insert ("--verbose", at: 1)
    }
    withUnsafePtr(strings: copy) { ptr in
        godot_main (Int32 (copy.count), ptr)
    }
}

I try to write a c++ version:

GDExtensionBool my_extension_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization* r_initialization) {
    if (p_get_proc_address) {
        //setExtensionInterface(p_get_proc_address, p_library);
        if (r_initialization != nullptr) {
            r_initialization->minimum_initialization_level = GDEXTENSION_INITIALIZATION_CORE;
            r_initialization->userdata = nullptr;
            r_initialization->initialize = &embeddedExtensionInit;
            r_initialization->deinitialize = &embeddedExtensionDeinit;
        }
        //return GDExtensionBool::GDExtensionTrue;
        return 1;
    }
    return 0;
}

void runGodot(std::vector<std::string> args, InitHookFunc initHook, LoadSceneFunc loadScene, LoadProjectSettingsFunc loadProjectSettings, bool verbose) {
    /* if (!g_loadScene) {
         std::cout << " was already invoked, it can currently only be invoked once" << std::endl;
         return;
     }*/
    g_loadScene = loadScene;
    g_loadProjectSettings = loadProjectSettings;
    g_initHook = initHook;

    libgodot_gdextension_bind(my_extension_init, [](void* startup) {
            if (g_loadScene && startup) {
                g_loadScene(startup);
            }
        }
    );

    args.insert(args.begin(), "Kit");
    if (verbose) {
        args.insert(args.begin() + 1, "--verbose");
    }

    char** argv = new char* [args.size()];
    for (size_t i = 0; i < args.size(); ++i) {
        argv[i] = const_cast<char*>(args[i].c_str());
    }
    godot_main(args.size(), argv);
    delete[] argv;
}

my question is : in swift version there is a setExtensionInterface(p_get_proc_address, p_library); this function I cannot find in the libgodot sourcecode and also in the swift code

wish your reply

### Steps to reproduce

null

### Minimal reproduction project

null

**Comment by FashGek** [comment] 2024-02-19 15:16
sorry, the format of the code is not good

**Comment by migueldeicaza** [comment] 2024-02-25 21:03
Not a bug, closing.   Feel free to discuss in the forums.

**Closed as completed by migueldeicaza** 2024-02-25 21:03 UTC
